services:
  # The Backend Spring Boot Web Service
  - type: web
    name: automart-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free # Deploys on Render's Free tier
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql-3cf5eb6c-avinashkatta05-f56f.h.aivencloud.com:12516/defaultdb?useSSL=true&verifyServerCertificate=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: avnadmin
      - key: SPRING_DATASOURCE_PASSWORD
        sync: true # Render will securely prompt you to input your Aiven database password during deployment
      - key: FRONTEND_URL
        value: https://automart-front.vercel.app # Override this with your actual live Vercel URL
      - key: RAZORPAY_API_SECRET
        sync: false
